-- Création de la base de données
CREATE DATABASE GestionCommerciale;
USE GestionCommerciale;

-- Table CLIENTS
DROP TABLE IF EXISTS `client`;
CREATE TABLE IF EXISTS `client` (
    IDCLIENT INT AUTO_INCREMENT PRIMARY KEY,
    RAISONSOCIALE VARCHAR(50) NOT NULL,
    ADRESSECLIENT VARCHAR(100),
    VILLECLIENT VARCHAR(50),
    TELEPHONECLIENT VARCHAR(15),
    TYPECLIENT VARCHAR(20) NOT NULL -- Exemple : "Entreprise" ou "Particulier"
)ENGINE=InnoDB AUTO_INCREMENT=60 DEFAULT CHARSET=latin1;

-- Table PROJETS
DROP TABLE IF EXISTS `projet`;
CREATE TABLE IF EXISTS `projet` (
    IDPROJET INT AUTO_INCREMENT PRIMARY KEY,
    NOMPROJET VARCHAR(50) NOT NULL,
    DATEDEBUT DATE,
    DATEFIN DATE,
    STATUTPROJET VARCHAR(20), -- Exemple : "En cours", "Terminé", etc.
    IDCLIENT INT, -- Clé étrangère vers CLIENTS
    FOREIGN KEY (IDCLIENT) REFERENCES CLIENTS(IDCLIENT) ON DELETE CASCADE
)ENGINE=InnoDB AUTO_INCREMENT=60 DEFAULT CHARSET=latin1;
